### ISSUE TITLE
Panels should have classes with names too

### ISSUE THREAD

**Issue by mihai-stancu** [Formfeed-UK/nova-theming-classes#2]
Hi,

Do you mind if I draw up a PR adding the name of the panel as a class?

Or perhaps the `$props?.name` for every component (if available)...

**Comment by ianrobertsFF** [comment]
Sure, happy to take a look at any PR for any additional classes that you need

**Comment by ianrobertsFF** [comment]
Implemented in v1.0.1, thanks!

**Comment by mihai-stancu** [comment]
10q!
