### ISSUE TITLE
Theming classes for Sidebar menu Items

### ISSUE THREAD

**Issue by atmediauk** [Formfeed-UK/nova-theming-classes#5]
Hello,

Is it possible to add identifying classes to sidebar menu items for greater styling control? (https://nova.laravel.com/docs/4.0/customization/menus.html#customizing-the-main-menu)

Thanks for your time.

**Comment by ianrobertsFF** [comment]
They actually already have some.

Nova itself provides: `sidebar-menu`, `sidebar-section`, `sidebar-group`, `sidebar-item`, `sidebar-item-title`, `sidebar-item-label`, `sidebar-item-icon`, etc

This package provides: `component-menu-section`, `component-menu-group`, `component-menu-item`

What further classes did you need?

**Comment by atmediauk** [comment]
> They actually already have some.
> 
> Nova itself provides: `sidebar-menu`, `sidebar-section`, `sidebar-group`, `sidebar-item`, `sidebar-item-title`, `sidebar-item-label`, `sidebar-item-icon`, etc
> 
> This package provides: `component-menu-section`, `component-menu-group`, `component-menu-item`
> 
> What further classes did you need?

Thanks, I was looking for a unique class for each menu item so their contents can be targeted/ styled individually.

**Comment by ianrobertsFF** [comment]
Ahh okay, that makes sense, ill take a look and see whats available. It'll probably just be a kebab casing of the "Name" prop of the MenuItem/Section/Group. That work for you?

**Comment by atmediauk** [comment]
> Ahh okay, that makes sense, ill take a look and see whats available. It'll probably just be a kebab casing of the "Name" prop of the MenuItem/Section/Group. That work for you?

That would be perfect, thank you!
